FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=securepassword123
ENV N8N_HOST=0.0.0.0
ENV WEBHOOK_URL=https://YOUR-APP-NAME.up.railway.app
ENV N8N_PORT=5678
ENV GENERIC_TIMEZONE=Europe/Warsaw